name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up PHP, Composer, Node.js, and npm
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Adjust to your PHP version
        tools: composer,nodejs

    - name: Install MySQL Client
      run: sudo apt-get install mysql-client

    - name: Install Laravel Dependencies
      run: |
        composer install
        npm install
    
    - name: SSH into EC2 and Execute Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user  # or your SSH username
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            sudo yum install ansible -y
            sudo yum install git -y
            mkdir Project
            cd Project/
            git init
            git config --global user.name Vaibhav
            git config --global user.email Vaibhav@gmail.com
            git remote add origin https://github.com/divyanshu-arya/laravelwebapp.git
            git config --global init.defaultBranch main
            git pull origin main
